version: '3.8'

services:
  postgres:
    image: postgres:13
    restart: always
    container_name: postgres-order-manager
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - order-network

  app:
    build:
      context: .
    container_name: order-manager-app
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: orderdb
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - order-network

networks:
  order-network:
    driver: bridge
